// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxtxyqrbciogdqehatbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4dHh5cXJiY2lvZ2RxZWhhdGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjkwNDksImV4cCI6MjA2MjEwNTA0OX0.PSG7K3qABRAMq-9_dX932bS4LEOwraZXLim8O0rVs-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);